-- MySQL Script generated by MySQL Workbench
-- 12/01/17 12:30:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gddmanager-dev
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gddmanager-dev` ;

-- -----------------------------------------------------
-- Schema gddmanager-dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gddmanager-dev` DEFAULT CHARACTER SET utf8mb4;
USE `gddmanager-dev` ;

-- -----------------------------------------------------
-- Table `company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `company` ;

CREATE TABLE IF NOT EXISTS `company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `referral_id` INT NULL,
  `name` TEXT NULL,
  `slogan` TEXT NULL,
  `email` VARCHAR(255),
  `address1` TEXT NULL,
  `address2` TEXT NULL,
  `city` TEXT NULL,
  `state` TEXT NULL,
  `country` TEXT NULL,
  `zip` TEXT NULL,
  `timezone` TEXT NULL,
  `website` TEXT NULL,
  `phone` TEXT NULL,
  `paypal_email` VARCHAR(255),
  `membership` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `month_users` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_company_referral_idx` (`referral_id` ASC),
  CONSTRAINT `fk_company_referral`
    FOREIGN KEY (`referral_id`)
    REFERENCES `company` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `password` TEXT NULL,
  `name` TEXT NULL,
  `roles` TEXT NULL,
  `activity` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `location` TEXT NULL,
  `language` VARCHAR(5) NOT NULL DEFAULT 'en',
  `timezone` TEXT NULL,
  `worktime` DOUBLE NULL,
  `workdays` TEXT NULL,
  `salary` DOUBLE NULL,
  `token` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_company_idx` (`company_id` ASC),
  CONSTRAINT `fk_user_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `company` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timesheet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timesheet` ;

CREATE TABLE IF NOT EXISTS `timesheet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `time` INT NOT NULL,
  `task` TEXT NOT NULL,
  `task_id` INT NOT NULL,
  `state` TEXT NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_area_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_area_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `message` ;

CREATE TABLE IF NOT EXISTS `message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_from_id` INT NOT NULL,
  `user_to_id` INT NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `message` TEXT NOT NULL,
  `read` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_message_user_from_idx` (`user_from_id` ASC),
  INDEX `fk_message_user_to_idx` (`user_to_id` ASC),
  CONSTRAINT `fk_message_user_from`
    FOREIGN KEY (`user_from_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user_to`
    FOREIGN KEY (`user_to_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project` ;

CREATE TABLE IF NOT EXISTS `project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `name` TEXT NULL,
  `team` TEXT NULL,
  `leader_id` INT NULL,
  `status` INT NOT NULL DEFAULT '0',
  `copyright` TEXT NULL,
  `version` TEXT NULL,
  `changes` TEXT NULL,
  `date` DATETIME NULL,
  `concept` TEXT NULL,
  `features` TEXT NULL,
  `genre` TEXT NULL,
  `audience` TEXT NULL,
  `look` TEXT NULL,
  `progression` TEXT NULL,
  `objectives` TEXT NULL,
  `flow` TEXT NULL,
  `physics` TEXT NULL,
  `movement` TEXT NULL,
  `economy` TEXT NULL,
  `combat` TEXT NULL,
  `switches` TEXT NULL,
  `pick` TEXT NULL,
  `talk` TEXT NULL,
  `read` TEXT NULL,
  `options` TEXT NULL,
  `save` TEXT NULL,
  `cheats` TEXT NULL,
  `backstory` TEXT NULL,
  `plot` TEXT NULL,
  `license` TEXT NULL,
  `screen_flow` TEXT NULL,
  `HUD` TEXT NULL,
  `rendering` TEXT NULL,
  `camera` TEXT NULL,
  `lighting` TEXT NULL,
  `controls` TEXT NULL,
  `help` TEXT NULL,
  `target_hardware` TEXT NULL,
  `dev_enviroment` TEXT NULL,
  `dev_standards` TEXT NULL,
  `engine` TEXT NULL,
  `network` TEXT NULL,
  `conventions` TEXT NULL,
  `style` TEXT NULL,
  `budget` DOUBLE NULL,
  `monetization` TEXT NULL,
  `risks` TEXT NULL,
  `marketing` TEXT NULL,
  `production_date` DATETIME NULL,
  `launch_date` DATETIME NULL,
  `price` DOUBLE NULL,
  `currency` TEXT NOT NULL,
  `public` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_project_company1_idx` (`company_id` ASC),
  INDEX `fk_project_leader1_idx` (`leader_id` ASC),
  CONSTRAINT `fk_project_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `company` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_leader1`
    FOREIGN KEY (`leader_id`)
    REFERENCES `user` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource` ;

CREATE TABLE IF NOT EXISTS `resource` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `name` TEXT NULL,
  `description` TEXT NULL,
  `units` TEXT NULL,
  `cost` DOUBLE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_resource_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_resource_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `character`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `character` ;

CREATE TABLE IF NOT EXISTS `character` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `name` TEXT NULL,
  `attributes_list` TEXT NULL,
  `state_machine` TEXT NULL,
  `backstory` TEXT NULL,
  `personality` TEXT NULL,
  `characteristics` TEXT NULL,
  `abilities` TEXT NULL,
  `relevance` TEXT NULL,
  `relationship` TEXT NULL,
  `statistics` TEXT NULL,
  `ai_type` TEXT NULL,
  `ai_collition` TEXT NULL,
  `ai_pathfinding` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_characters_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_characters_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enviroment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enviroment` ;

CREATE TABLE IF NOT EXISTS `enviroment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `name` TEXT NULL,
  `attributes_list` TEXT NULL,
  `characteristics` TEXT NULL,
  `relevance` TEXT NULL,
  `relationship` TEXT NULL,
  `statistics` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_enviroment_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_enviroment_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `area` ;

CREATE TABLE IF NOT EXISTS `area` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `name` TEXT NULL,
  `description` TEXT NULL,
  `characteristics` TEXT NULL,
  `connections` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_area_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_area_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `level` ;

CREATE TABLE IF NOT EXISTS `level` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `user_id` INT NULL,
  `area_id` INT NULL,
  `enviroment` TEXT NULL,
  `characters` TEXT NULL,
  `graphics` TEXT NULL,
  `music` TEXT NULL,
  `sounds` TEXT NULL,
  `cutscenes` TEXT NULL,
  `name` TEXT NULL,
  `synopsis` TEXT NULL,
  `introduction` TEXT NULL,
  `objectives` TEXT NULL,
  `description` TEXT NULL,
  `path` TEXT NULL,
  `encounters` TEXT NULL,
  `walkthrough` TEXT NULL,
  `closing` TEXT NULL,
  `design` TEXT NULL,
  `finish` TINYINT(1) NOT NULL DEFAULT 0,
  `code` TINYINT(1) NOT NULL DEFAULT 0,
  `valid` TINYINT(1) NOT NULL DEFAULT 0,
  `test` TINYINT(1) NOT NULL DEFAULT 0,
  `time` INT NULL,
  `time_est` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_level_project1_idx` (`project_id` ASC),
  INDEX `fk_level_user1_idx` (`user_id` ASC),
  INDEX `fk_level_area1_idx` (`area_id` ASC),
  CONSTRAINT `fk_level_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `area` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_level_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_level_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `screen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `screen` ;

CREATE TABLE IF NOT EXISTS `screen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `user_id` INT NULL,
  `graphics` TEXT NULL,
  `sounds` TEXT NULL,
  `music` TEXT NULL,
  `name` TEXT NULL,
  `description` TEXT NULL,
  `file` TEXT NULL,
  `finish` TINYINT(1) NOT NULL DEFAULT 0,
  `code` TINYINT(1) NOT NULL DEFAULT 0,
  `valid` TINYINT(1) NOT NULL DEFAULT 0,
  `test` TINYINT(1) NOT NULL DEFAULT 0,
  `time` INT NULL,
  `time_est` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_screen_project1_idx` (`project_id` ASC),
  INDEX `fk_screen_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_screen_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_screen_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cutscene`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cutscene` ;

CREATE TABLE IF NOT EXISTS `cutscene` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `user_id` INT NULL,
  `actors` TEXT NULL,
  `enviroment` TEXT NULL,
  `graphics` TEXT NULL,
  `music` TEXT NULL,
  `sounds` TEXT NULL,
  `description` TEXT NULL,
  `storyboard` TEXT NULL,
  `script` TEXT NULL,
  `finish` TINYINT(1) NOT NULL DEFAULT 0,
  `sketch` TINYINT(1) NOT NULL DEFAULT 0,
  `code` TINYINT(1) NOT NULL DEFAULT 0,
  `valid` TINYINT(1) NOT NULL DEFAULT 0,
  `test` TINYINT(1) NOT NULL DEFAULT 0,
  `time` INT NULL,
  `time_est` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cutscene_project1_idx` (`project_id` ASC),
  INDEX `fk_cutscen_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_cutscene_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cutscen_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dialog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dialog` ;

CREATE TABLE IF NOT EXISTS `dialog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `user_id` INT NULL,
  `character_id` INT NULL,
  `name` TEXT NULL,
  `context` TEXT NULL,
  `content` TEXT NULL,
  `finish` TINYINT(1) NOT NULL DEFAULT 0,
  `code` TINYINT(1) NOT NULL DEFAULT 0,
  `valid` TINYINT(1) NOT NULL DEFAULT 0,
  `test` TINYINT(1) NOT NULL DEFAULT 0,
  `time` INT NULL,
  `time_est` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dialog_project1_idx` (`project_id` ASC),
  INDEX `fk_dialog_user1_idx` (`user_id` ASC),
  INDEX `fk_dialog_character1_idx` (`character_id` ASC),
  CONSTRAINT `fk_dialog_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dialog_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dialog_character1`
    FOREIGN KEY (`character_id`)
    REFERENCES `character` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `graphic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graphic` ;

CREATE TABLE IF NOT EXISTS `graphic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NULL,
  `user_id` INT NULL,
  `name` TEXT NULL,
  `description` TEXT NULL,
  `file` TEXT NULL,
  `sketch` TINYINT(1) NOT NULL DEFAULT 0,
  `valid` TINYINT(1) NOT NULL DEFAULT 0,
  `finish` TINYINT(1) NOT NULL DEFAULT 0,
  `time` INT NULL,
  `time_est` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_graphic_project1_idx` (`project_id` ASC),
  INDEX `fk_graphic_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_graphic_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_graphic_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sound`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sound` ;

CREATE TABLE IF NOT EXISTS `sound` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `user_id` INT NULL,
  `name` TEXT NULL,
  `description` TEXT NULL,
  `file` TEXT NULL,
  `finish` TINYINT(1) NOT NULL DEFAULT 0,
  `valid` TINYINT(1) NOT NULL DEFAULT 0,
  `time` INT NULL,
  `time_est` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sound_project1_idx` (`project_id` ASC),
  INDEX `fk_sound_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_sound_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sound_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `music` ;

CREATE TABLE IF NOT EXISTS `music` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `user_id` INT NULL,
  `name` TEXT NULL,
  `description` TEXT NULL,
  `file` TEXT NULL,
  `finish` TINYINT(1) NOT NULL DEFAULT 0,
  `valid` TINYINT(1) NOT NULL DEFAULT 0,
  `time` INT NULL,
  `time_est` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_music_project1_idx` (`project_id` ASC),
  INDEX `fk_music_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_music_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_music_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `component`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `component` ;

CREATE TABLE IF NOT EXISTS `component` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `user_id` INT NULL,
  `dependency_id` INT NULL,
  `character_id` INT NULL,
  `enviroment_id` INT NULL,
  `screen_id` INT NULL,
  `level_id` INT NULL,
  `cutscene_id` INT NULL,
  `sounds` TEXT NULL,
  `graphics` TEXT NULL,
  `name` TEXT NULL,
  `description` TEXT NULL,
  `code` TINYINT(1) NOT NULL DEFAULT 0,
  `valid` TINYINT(1) NOT NULL DEFAULT 0,
  `test` TINYINT(1) NOT NULL DEFAULT 0,
  `time` INT NULL,
  `time_est` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_component_project1_idx` (`project_id` ASC),
  INDEX `fk_component_user1_idx` (`user_id` ASC),
  INDEX `fk_component_component1_idx` (`dependency_id` ASC),
  INDEX `fk_component_character1_idx` (`character_id` ASC),
  INDEX `fk_component_enviroment1_idx` (`enviroment_id` ASC),
  INDEX `fk_component_screen1_idx` (`screen_id` ASC),
  INDEX `fk_component_level1_idx` (`level_id` ASC),
  INDEX `fk_component_cutscene1_idx` (`cutscene_id` ASC),
  CONSTRAINT `fk_component_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_component_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_component_component1`
    FOREIGN KEY (`dependency_id`)
    REFERENCES `component` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_component_character1`
    FOREIGN KEY (`character_id`)
    REFERENCES `character` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_component_enviroment1`
    FOREIGN KEY (`enviroment_id`)
    REFERENCES `enviroment` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_component_screen1`
    FOREIGN KEY (`screen_id`)
    REFERENCES `screen` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_component_level1`
    FOREIGN KEY (`level_id`)
    REFERENCES `level` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_component_cutscene1`
    FOREIGN KEY (`cutscene_id`)
    REFERENCES `cutscene` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bug`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bug` ;

CREATE TABLE IF NOT EXISTS `bug` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `user_id` INT NULL,
  `description` TEXT NULL,
  `trigger` TEXT NULL,
  `severity` INT NULL,
  `message` TEXT NULL,
  `picture` TEXT NULL,
  `code` TINYINT(1) NOT NULL DEFAULT 0,
  `test` TINYINT(1) NOT NULL DEFAULT 0,
  `time` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bug_project1_idx` (`project_id` ASC),
  INDEX `fk_bug_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_bug_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bug_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `task` ;

CREATE TABLE IF NOT EXISTS `task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  	  `user_id` INT NULL,
  `name` TEXT NULL,
  `description` TEXT NULL,
  `deadline` DATETIME NULL,
  `finish` TINYINT(1) NOT NULL DEFAULT 0,
  `time` INT NULL,
  `time_est` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task_project1_idx` (`project_id` ASC),
  INDEX `fk_task_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_task_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_user1`
	FOREIGN KEY (`user_id`)
	REFERENCES `user` (`id`)
	ON DELETE CASCADE
	ON UPDATE NO ACTION)
	ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `change`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `change` ;

CREATE TABLE IF NOT EXISTS `change` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task` TEXT NOT NULL,
  `task_id` INT NOT NULL,
  `description` TEXT NULL,
  `file` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marketing` ;

CREATE TABLE IF NOT EXISTS `marketing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `logo_icon` TEXT NULL,
  `images` TEXT NULL,
  `videos` TEXT NULL,
  `target_audience` TEXT NULL,
  `art_style` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_marketing_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_marketing_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `section` ;

CREATE TABLE IF NOT EXISTS `section` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `section_id` INT NOT NULL,
  `name` TEXT NULL,
  `content` TEXT NULL,
  `file` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_section_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_section_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
